# Generated by Django 5.0.6 on 2024-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW3app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
